version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: negative777/backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    env_file: .env
    image: negative777/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/app/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
