# Generated by Django 4.2.4 on 2023-08-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='model',
        ),
    ]
