# Generated by Django 4.2.4 on 2023-08-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscribe_subscribe_unique_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscription', to='users.subscribe', verbose_name='Подписка'),
        ),
    ]
